# Generated by Django 2.0.3 on 2018-03-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0003_asset_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.Info')),
                ('notification_type', models.CharField(choices=[('debug', 'Debug'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'info'), ('success', 'Sucess')], default='info', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
            bases=('info.info',),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.Info')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Updates',
                'verbose_name': 'Update',
                'ordering': ['-created_at'],
            },
            bases=('info.info',),
        ),
        migrations.AddField(
            model_name='info',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
        ),
        migrations.AddField(
            model_name='info',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='info',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Section'),
        ),
    ]
