# Generated by Django 2.0.3 on 2018-03-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180328_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date'], 'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.RenameField(
            model_name='update',
            old_name='created_at',
            new_name='date',
        ),
    ]
