# Generated by Django 2.0.3 on 2018-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180328_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('debug', 'Debug'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Sucess')], default='info', max_length=7),
        ),
    ]
