# Generated by Django 2.0.3 on 2018-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20180413_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
