# Generated by Django 2.0.3 on 2018-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_section_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
