# Generated by Django 2.0.3 on 2018-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='plan',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
