# Generated by Django 2.0.3 on 2018-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180411_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='plan_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='plan_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
