# Generated by Django 2.0.3 on 2018-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20180510_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('room', 'Room'), ('area', 'Area'), ('desk', 'Desk')], default='employ', max_length=5),
        ),
    ]
