# Generated by Django 2.0.3 on 2018-03-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.Asset')),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('serial', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('hdd', models.CharField(blank=True, max_length=200, null=True)),
                ('buyed_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hardware',
                'verbose_name': 'Hardware',
                'ordering': ['-created_at'],
            },
            bases=('asset.asset',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.Asset')),
                ('license', models.CharField(blank=True, max_length=200, null=True)),
                ('license_amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Software',
                'verbose_name': 'Software',
                'ordering': ['-created_at'],
            },
            bases=('asset.asset',),
        ),
    ]
