# Generated by Django 2.0.3 on 2018-03-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desk.Desk'),
        ),
    ]
