# Generated by Django 2.0.3 on 2018-03-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
    ]
