# Generated by Django 2.0.3 on 2018-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_remove_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='ssd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
