# Generated by Django 2.0.3 on 2018-03-28 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
    ]
