# Generated by Django 2.0.3 on 2018-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20180328_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='buyed_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
