# Generated by Django 2.0.3 on 2018-04-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20180403_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='buyed_at',
            new_name='bought_at',
        ),
    ]
