# Generated by Django 2.0.3 on 2018-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20180403_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='bought_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
