# Generated by Django 2.0.3 on 2018-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='section',
        ),
    ]
