# Generated by Django 2.0.3 on 2018-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_remove_request_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
    ]
