# Generated by Django 2.0.3 on 2018-06-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20180607_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Hardware'),
        ),
    ]
