# Generated by Django 2.0.10 on 2019-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_auto_20180613_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='guarantee_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
